version: '3.10'
services:
  web:
    image: nginx:latest
    volumes:
      - /var/projects/telebotdocker/site.conf:/etc/nginx/conf.d/site.conf
      - ./app:/app
    depends_on:
      - phpfpm

  phpfpm:
    image: bitnami/php-fpm:latest
    volumes:
      - ./core:/core
      - ./app:/app
