version: '3.9'
services:
  web:
    image: nginx:latest
    volumes:
      - ./configs/site.conf:/etc/nginx/conf.d/site.conf:ro
      - ./configs/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf:ro
      - ./app:/app:mo
    ports:
      - "8005:80"
    depends_on:
      - phpfpm
    networks:
      - app_tier

  db:
    image: bitnami/mariadb:latest
    volumes:
      - ./data:/bitnami/mariadb
#      - /configs/db.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf:ro
    env_file:
      - ./configs/db.env
    networks:
      - db_tier

  phpfpm:
    image: bitnami/php-fpm:latest
    volumes:
#      - ./core:/core
      - ./app:/app
    networks:
      - db_tier
      - app_tier

networks:
  app_tier:
    driver: bridge
  db_tier:
    driver: bridge